version: 2.1

orbs:
  android: circleci/android@2.3.0

commands:
  install_java_package:
    steps:
      - run:
          name: Cài đặt java package
          command: |
            sudo apt-get update
            sudo apt-get install maven openjdk-17-jdk git -y
            sudo apt-get install python3 python3-pip -y
            pip3 install paramiko requests
jobs:
  android-test:
    executor:
      name: android/android-machine
      tag: 2021.10.1
    steps:
      - checkout
      - android/start-emulator-and-run-tests:
          test-command: ./gradlew connectedDebugAndroidTest
          system-image: system-images;android-30;google_apis;x86
  release-build:
    executor:
      name: android/android-machine
      tag: 2021.10.1
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - run:
          name: Assemble release build
          command: |
            ./gradlew assembleRelease
      - store_artifacts:
          path: app/build/outputs/apk/release
workflows:
  release-build-flowsg:
    jobs:
      - android-test:
          filters:
            branches:
              only:
                - deployment
      - release-build:
          requires:
            - android-test

